[FIX] Add (required) `shell` module to minilib.
Prior to this commit, installing from a `tar` distribution using
`easy_install` or `pip` without `paver` installed _(i.e., using
`paver-minilib.zip`) caused the following exception to occur:

    ImportError: No module named shell

Adding `shell` to the list of modules to include when generating
`paver-minilib.zip` fixes this issue.